### ISSUE TITLE
The BuildkiteBuildsTable shows all builds in buildkite, instead of the selected service

### ISSUE THREAD

**Issue by MrFatt** [RoadieHQ/backstage-plugin-buildkite#7]
Hi there, thanks for creating this plugin!

When I was integrating this plugin in my backstage app, i found all the builds under my organization were shown up in the CI/CD tab. In my understanding, it should only shows the builds of that service.

And I noticed that, in the `getBuilds` function, the `orgSlug` and `pipelineSlug` are not passed to buildkite API [here](https://github.com/RoadieHQ/backstage-plugin-buildkite/blob/main/src/api/index.ts#L48-L52)

Is this deliberate or a bug?

**Comment by lewtakm** [comment]
@MrFatt thank you for a report. I updated the plugin and now it fetch only selected pipeline builds. New package in available on the NPM now.
